# Generated by Django 4.2.4 on 2023-09-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
            preserve_default=False,
        ),
    ]
